name: Render Mermaid diagrams

on:
  push:
    paths:
      - 'diagrams/**/*.mmd'
      - '.github/workflows/render-mermaid.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install mermaid-cli
        run: npm install -g @mermaid-js/mermaid-cli
      - name: Render .mmd to .svg
        run: |
          mkdir -p diagrams
          for f in $(find diagrams -name '*.mmd'); do
            out="${f%.mmd}.svg"
            echo "Rendering $f -> $out"
            mmdc -i "$f" -o "$out"
          done
      - name: Commit rendered SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add diagrams/*.svg || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: render Mermaid diagrams"
            git push
          fi
